server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ollama-route
          uri: http://localhost:11434
          predicates:
            - Path=/ollama/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: localhost
      port: 6379
      # password: 비밀번호 사용 시, 나중에 추가